### ISSUE TITLE
configuration :  set :pg_user   not working

### ISSUE THREAD

**Issue by erwin16** [capistrano-plugins/capistrano-postgresql#19]
It's stted in the doc :+1: 
set :pg_user
Name of the database user. Defaults to whatever is set for pg_database option.

so when I write in my config/deploy/production.rb

set :pg_user, 'deploy'

I should get it ... but rather it's sticked to the pg_database name..

/home/deploy/apps/simpleapp_production/db/database.yml
production:
  adapter: postgresql
  encoding: unicode
  database: simpleapp_production
  pool: 5
  username: simpleapp_production
  password: '42bcd780cc6aa2250b5b'
  host: localhost

**Comment by Jonybang** [comment]
+
i think problem in:
https://github.com/capistrano-plugins/capistrano-postgresql/blob/a843c0fd9def47fbbb3496a3354d0b1fd01e8265/lib/capistrano/tasks/postgresql.rake#L12

**Comment by agm1988** [comment]
same issue here but with :pg_pool option

**Comment by NorseGaud** [comment]
Are these issues still happening?
@agm1988 
@erwin16

**Comment by agm1988** [comment]
@NorseGaud no, not faced that issue on recent projects.
