### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by ricardocastaneda** [capistrano-plugins/capistrano-postgresql#20]
When you don't have db role in `config/deploy/production.rb`, it gives you a "TypeError: no implicit conversion of nil into String". 
For accident I didn't have it and faced this problem. It is something obvious but I think it should be documented.

`server '111.111.11.11', user: 'deploy', roles: %w{web app db}`

**Comment by nmcalabroso** [comment]
I just encountered this and yes, the fix mentioned by the OP worked. Thanks!

**Comment by NorseGaud** [comment]
@nmcalabroso , what situations would you not have a db role and want to use this gem? I'm concerned this isn't actually an issue we can address in the code. Maybe notify the user they need to have a db role with a raise.

**Comment by NorseGaud** [comment]
Fixed in v4.9.0
