### ISSUE TITLE
Setup freezes with md5 Authentication

### ISSUE THREAD

**Issue by ricardocastaneda** [capistrano-plugins/capistrano-postgresql#21]
When my Postgres uses md5 Authentication my cap production setup freezes asking for password, but setup works when I set Authentication to "trust".
Can you suggest the correct config I should have, md5 or trust?

**Comment by slytton** [comment]
I'm having the same issue. Were you able to find a fix?

**Comment by ricardocastaneda** [comment]
No. I left the Authentication with "trust".

**Comment by NorseGaud** [comment]
I'm using ```host        all        all        0.0.0.0/0        md5``` and it's working fine.
Even trust.
@ricardocastaneda , can you replicate the issue and open a new issue? This one is so old I'm going to close it out.
