### ISSUE TITLE
Cannot load `Rails.application.database_configuration`

### ISSUE THREAD

**Issue by shenoudab** [capistrano-plugins/capistrano-postgresql#24]
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]

While i add config/database.yml to .gitignore and the postgresql.yml.erb is placed on config/deploy/templates

Also, how to install postgresql directly from capitsrano-postgresql.

looking for your help and support.

**Comment by NorseGaud** [comment]
Please reopen if the issue persists after installing the newest version of the gem.

It can't install postgressql for you. You should try using puppet to manage installation of postgressql and let this gem handle the rest.
