### ISSUE TITLE
/db/database.yml: No such file or directory

### ISSUE THREAD

**Issue by mcmegavolt** [capistrano-plugins/capistrano-postgresql#27]
I get this error when trying to `cap production setup`

```
cap aborted!
scp: ~/www/my_app/db/database.yml: No such file or directory
```

I have this config line in my deploy.rb

``` ruby
set :linked_files, fetch(:linked_files, []).push('config/database.yml')
```

My Gemfile:

``` ruby
  gem 'capistrano', '~> 3.4'
  gem 'capistrano-postgresql', '~> 4.2.0
  ...
```

**Comment by dfang** [comment]
+1

**Comment by NorseGaud** [comment]
~ isn't allowed in the :deploy_to. You need to use the absolute path with /home/your_user/

**Comment by NorseGaud** [comment]
Will notify you with a raise once we merge in https://github.com/capistrano-plugins/capistrano-postgresql/pull/35

**Comment by bruno-** [comment]
Hi @NorseGaud, I've invited you as a collaborator for this repo.
