### ISSUE TITLE
Doesn't fetch data from :rails_env

### ISSUE THREAD

**Issue by Lyubomyr** [capistrano-plugins/capistrano-postgresql#28]
Hello.
I am using rails 4 and last versions of capistrano and capistrano-postgresql. And I want to use "prod" staging. But, every time when I am runnig `cap prod postgresql:generate_database_yml` command, it creating me a database.yml like this:

```
prod:
  adapter: postgresql
  encoding: utf8
  database: team_work_prod
  ...
```

So, this causing an error, because there is no "prod" environment. I have set `set :rails_env, 'production'` in prod.rb and also tried set `set :pg_templates_path, "deploy/config/templates"` or `set :pg_env, fetch(:rails_env)`, but nothing changed. I also tried to move all this settings from env file to deploy.rb file or even into Capfile - result the same, only default options copied into database.yml.

I am using pretty standard capistrano workflow, the only custom thing - that I moved deploy folder into my rails application root folder and using separate Gemfile for it (without rails gem). But, not sure why this can cause issues, because I am using a lot of capistrano plugins and they are configuring and working well. Can you advise where to search?

**Comment by NorseGaud** [comment]
I believe it uses the file name. Can you change prod.rb to production.rb?
Let me know if that doesn't fix it.
