### ISSUE TITLE
password authentication failed for user "..."

### ISSUE THREAD

**Issue by pitops** [capistrano-plugins/capistrano-postgresql#30]
I am running into an issue. After running "bundle exec cap production deploy" and it finishes successfully for some reason i am getting the message

> PG::ConnectionBad: FATAL:  password authentication failed for user "..."
> FATAL:  password authentication failed for user "..."

anyone care to enlighten me as to why is that?

**Comment by nmcalabroso** [comment]
Did you do the `cap production setup` first where capistrano will create a dedicated postgresql role for your database? Did it work?

**Comment by NorseGaud** [comment]
Closing. If you see this issue still, re-open the issue.
