### ISSUE TITLE
creating database user failed!

### ISSUE THREAD

**Issue by nmcalabroso** [capistrano-plugins/capistrano-postgresql#31]
```
neil@my-computer:~/Projects/app 
⇒  cap production postgresql:create_db_user
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.3.1
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
00:00 postgresql:create_db_user
      postgresql: creating database user failed!
```

capistrano 3.6.1
capistrano-postgresql 4.2.1
postgresql 9.5.4

Checking [this](https://github.com/capistrano-plugins/capistrano-postgresql/blob/master/lib/capistrano/tasks/postgresql.rake#L97), I'm not really sure how would this work without using the system user `postgres` (for ubuntu). Any luck to solve this issue?

**Comment by nmcalabroso** [comment]
apparently, `psql` function is calling [this](https://github.com/capistrano-plugins/capistrano-postgresql/blob/master/lib/capistrano/postgresql/psql_helpers.rb#L25).

**Comment by nmcalabroso** [comment]
So here's the function that gets called when executing the `psql` function in capistrano tasks.
```
def psql_on_db(db_name, *args)
        test :sudo, "-u #{fetch(:pg_system_user)} psql -d #{db_name}", *args
end
```
The problem here is that we're assuming that the database already exists while creating a new user.

This is the setup phase:
```
desc 'Postgresql setup tasks'
  task :setup do
    invoke "postgresql:create_db_user"
    invoke "postgresql:create_database"
    invoke 'postgresql:add_hstore'
    invoke 'postgresql:add_extensions'
    invoke "postgresql:generate_database_yml_archetype"
    invoke "postgresql:generate_database_yml"
end
```

**Comment by nmcalabroso** [comment]
I created a pull request for this. Hopefully, someone will merge or comment on this ASAP.

**Comment by NorseGaud** [comment]
@nmcalabroso , this, and much more, is resolved in pull/35

**Comment by NorseGaud** [comment]
Merged in your changes in my branch! Thanks!
