### ISSUE TITLE
postgresql:setup will failed if :pg_user is a name started with number

### ISSUE THREAD

**Issue by dfang** [capistrano-plugins/capistrano-postgresql#34]
if set :application, '700stone'
```
> cap production postgresql:setup --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rbenv:validate (first_time)
** Execute rbenv:validate
** Invoke rbenv:map_bins (first_time)
** Execute rbenv:map_bins
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env
** Invoke production
** Invoke production
** Invoke postgresql:setup (first_time)
** Execute postgresql:setup
** Invoke postgresql:create_db_user (first_time)
** Execute postgresql:create_db_user
00:00 postgresql:create_db_user
      postgresql: creating database user failed!
```

changed to set :application, 'stone', ```cap production postgresql:setup --trace```succeed !

**Comment by dfang** [comment]
```
 desc 'Create DB user'
  task :create_db_user do
    on roles :db do
      next if db_user_exists? fetch(:pg_user)
      unless psql '-c', %Q{"CREATE user #{fetch(:pg_user)} WITH password '#{fetch(:pg_password)}';"}
        error 'postgresql: creating database user failed!'
        exit 1
      end
    end
  end
```


because ```psql -c "CREATE USER '700stone' WITH PASSWORD 'password'"``` will raise a syntax error.

**Comment by NorseGaud** [comment]
Strange, it works using createuser:
`-bash-4.2$ createuser 700stone
-bash-4.2$ createuser 700stone
createuser: creation of new role failed: ERROR:  role "700stone" already exists`

I'll take a look and follow up with what I find.

**Comment by NorseGaud** [comment]
> createuser is a wrapper around the SQL command CREATE ROLE. There is no effective difference between creating users via this utility and via other methods for accessing the server.
https://www.postgresql.org/docs/9.6/static/app-createuser.html

So I thought I'd play around and see if I could get it to accept integers. Likely we'll need to modify the CREATE USER in the master branch.

Here is what I found:

`-bash-4.2$ psql -c "CREATE ROLE 700stone PASSWORD \'testing123\';"
ERROR:  syntax error at or near "700"
LINE 1: CREATE ROLE 700stone PASSWORD \'testing123\';
                    ^`
`-bash-4.2$ psql -c "CREATE ROLE \"700stone\" PASSWORD \'testing123\';"
ERROR:  syntax error at or near "\"
LINE 1: CREATE ROLE "700stone" PASSWORD \'testing123\';
                                        ^`
`-bash-4.2$ psql -c "CREATE ROLE \"700stone\" PASSWORD 'testing123';"
ERROR:  role "700stone" already exists`
`-bash-4.2$ psql -c "CREATE ROLE \"700ston\" PASSWORD 'testing123';"
CREATE ROLE`
`-bash-4.2$ psql -c "CREATE USER \"700ston4\" PASSWORD 'testing123';"
CREATE ROLE`

I'll fix it in the master branch and do a pull request soon. For now, you'll need to fork and modify, updating the CREATE USER to escape the username section. Then build and install the modified gem locally.
