### ISSUE TITLE
Changelog and README missing information about v4.6.0

### ISSUE THREAD

**Issue by jesperronn** [capistrano-plugins/capistrano-postgresql#41]
Thanks for creating and maintaining this plugin 👍 

I updated my outdated rubygems for an application, and to my surprise, this plugin was released in version 4.6.0 (jumped from v4.2.1).

However, the README and Changelog has no information about either of them.

Could you add, or do you want help for that?

UPDATE: I see that Releases page contain at least some information about changes. If you want to maintain the releases pages, thats fine with me, even though it's Githubs' own proprietary way of showing changes (paginated and not necessarily complete).

I have these suggestions for the releases:

* be consistent about tags: all previous versions have their version number prepended with a "v", for instance `v4.3.0`. Newest version has forgotten the "v" and is only tagged as `4.6.0`. Suggestion: add the tag `v4.6.0`. You can use the one-liner: 

```
git tag v4.6.0 -m v4.6.0 e445285 && git push --follow-tags
```

* make releases easier to discover by updating the Changelog in the root folder. This is more discoverable when browsing the project. Furthermore, no relevant information is hidden by pagination or 'read more' links

**Comment by NorseGaud** [comment]
Thanks!

- The README does indicate all of the new features since I've been contributing.
- I've updated the Changelog with all of the recent additions
- I'll be sure to include v before tags.

**Comment by jesperronn** [comment]
Awesome! Thanks for updating!
