### ISSUE TITLE
Using incorrect database for checking/creating db and user when running without sudo

### ISSUE THREAD

**Issue by snake66** [capistrano-plugins/capistrano-postgresql#44]
Trying a fresh deploy without sudo on a FreeBSD system fails on version 4.6.1.

I have the following config for my system:

```ruby
set :pg_user, 'hmno_test'
set :pg_system_user, 'pgsql'
set :pg_ask_for_password, true
set :pg_without_sudo, true
```

Running the `postgresql:setup` task I get the following:

```
% bundle exec cap test postgresql:setup
* ============================= *
 All psql commands will be run without sudo
 You can modify this in your deploy/{env}.rb by setting the pg_without_sudo boolean
* ============================= *
...
DEBUG [6030dfb2] Running /usr/bin/env psql -d hmno_test -U pgsql -tAc "SELECT 1 FROM pg_roles WHERE rolname='hmno_test';" | grep -q 1 as deploy@volse.local
DEBUG [6030dfb2] Command: /usr/bin/env psql -d hmno_test -U pgsql -tAc "SELECT 1 FROM pg_roles WHERE rolname='hmno_test';" | grep -q 1
DEBUG [6030dfb2]        psql: FATAL:  database "hmno_test" does not exist
DEBUG [6030dfb2] Finished in 0.022 seconds with exit status 1 (failed).
Please enter pg_password (Postgresql database password for the app: ): ***************
DEBUG [1439ef10] Running /usr/bin/env psql -U pgsql -c "CREATE USER \"hmno_test\" PASSWORD '***************';" as deploy@volse.local
DEBUG [1439ef10] Command: /usr/bin/env psql -U pgsql -c "CREATE USER \"hmno_test\" PASSWORD '***************';"
DEBUG [1439ef10]        psql: FATAL:  database "pgsql" does not exist
DEBUG [1439ef10] Finished in 0.391 seconds with exit status 2 (failed).
ERROR postgresql: creating database user failed!
```

Here the line:

    /usr/bin/env psql -d hmno_test -U pgsql -tAc "SELECT 1 FROM pg_roles WHERE rolname='hmno_test';" | grep -q 1

Should have read:

    /usr/bin/env psql -d postgres -U pgsql ....

As that's where the `pg_roles` table is defined, not in the application db. Likewise the line:

    /usr/bin/env psql -U pgsql -c "CREATE USER \"hmno_test\" PASSWORD '***************';

Should read:

    /usr/bin/env psql -d postgres -U pgsql -c "CREATE USER...

Since it otherwise will try to use a database with the same name as the `:pg_system_user` (pgsql in this case.)

The solution should be to use `:pg_system_db` in `PsqlHelpers::db_user_exists?` and `PsqlHelpers::database_exists?`, and to use `psql_on_db` with the proper databse set in the `:create_db_user` and `:create_database` tasks too. I don't think being explicit like this should impact the "normal" case when running with sudo.

**Comment by NorseGaud** [comment]
Good catch. I see that I used pg_database instead of pg_system_db on those exists? helpers.

Though, I don't quite understand the need for the pg_on_db for create_db_user or create_database. I'm not seeing any errors running the current create_db_user.

**Comment by NorseGaud** [comment]
I ended up using `psql_on_db fetch(:pg_system_db)` on create* tasks. This seems to be working for me from my tests. Can you build 4.7.0 from source and give it a try for me @snake66?

**Comment by snake66** [comment]
Nathan Pierce <notifications@github.com> writes:

> I ended up using `psql_on_db fetch(:pg_system_db)` on create*
> tasks. This seems to be working for me from my tests. Can you build
> 4.7.0 from source and give it a try for me @snake66?

I will try to test it a bit later today. I did the same locally and that
seemed to work. I also had to change the
`:generate_database_yml_archetype` task to use the regular `upload!`
helper instead of the `Net::SCP`-stuff, but I'll look more into that and
make it a separate issue if needed.

-- 
Harald Eilertsen
PGP fingerprint: F5A3 1F60 A96A 5DC4 7E1E  A40A 256C C461 865C 31C4

Home: https://volse.anduin.net/~haraldei
Blog: https://volse.anduin.net/rabalder
Chat: harald@jabberpl.org (XMPP/jabber)

**Comment by snake66** [comment]
The version tagged 4.7.0 works for me when I duplicate the information from the server line into the `pg_host`and `system_user` vars.

**Comment by NorseGaud** [comment]
Sorry, what do you mean by the server line? Do I need to make more changes?

**Comment by snake66** [comment]
I'll post it in a new issue. It works like it is now, so let's leave it like it is for now :)
